# Build stage
FROM node:20 AS dev

# Set the working directory
WORKDIR /app

# Copy only the package.json and lock file to leverage Docker caching
COPY package.json pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the application
RUN pnpm run build

# Expose the default Nginx port
EXPOSE 5173

# Start Nginx
CMD ["pnpm", "run", "dev", "--host"]